### ISSUE TITLE
图片看不到。。。

### ISSUE THREAD

**Issue by allenChn** [codingdebugallday/data-lineage-parent#1]
好G友，能不能换个图片地址呢，咋样都看不到，谢谢！

**Comment by thestyleofme** [comment]
GitHub 访问不了图片，这个需要翻墙或者配置一下 hosts，百度可以解决，当一段时间后若又不能看到图片时，那么又需要修改下 hosts 文件了，我贴一下我的 hosts 吧

`# GitHub Start
140.82.114.3 github.com
140.82.113.4 gist.github.com
185.199.111.153 assets-cdn.github.com
151.101.248.133 raw.githubusercontent.com
151.101.208.133 gist.githubusercontent.com
151.101.248.133 cloud.githubusercontent.com
151.101.248.133 camo.githubusercontent.com
199.232.96.133 avatars.githubusercontent.com
151.101.248.133 avatars0.githubusercontent.com
151.101.248.133 avatars1.githubusercontent.com
151.101.208.133 avatars2.githubusercontent.com
151.101.208.133 avatars3.githubusercontent.com
151.101.248.133 avatars4.githubusercontent.com
151.101.208.133 avatars5.githubusercontent.com
151.101.208.133 avatars6.githubusercontent.com
151.101.248.133 avatars7.githubusercontent.com
151.101.248.133 avatars8.githubusercontent.com
185.199.110.154 github.githubassets.com
151.101.248.133 user-images.githubusercontent.com
140.82.113.10 codeload.github.com
140.82.121.6 api.github.com
# GitHub End`

**Comment by thestyleofme** [comment]
> 好G友，能不能换个图片地址呢，咋样都看不到，谢谢！

GitHub 访问不了图片，这个需要翻墙或者配置一下 hosts，百度可以解决，当一段时间后若又不能看到图片时，那么又需要修改下 hosts 文件了，我贴一下我的 hosts 吧

```
# GitHub Start
140.82.114.3 github.com
140.82.113.4 gist.github.com
185.199.111.153 assets-cdn.github.com
151.101.248.133 raw.githubusercontent.com
151.101.208.133 gist.githubusercontent.com
151.101.248.133 cloud.githubusercontent.com
151.101.248.133 camo.githubusercontent.com
199.232.96.133 avatars.githubusercontent.com
151.101.248.133 avatars0.githubusercontent.com
151.101.248.133 avatars1.githubusercontent.com
151.101.208.133 avatars2.githubusercontent.com
151.101.208.133 avatars3.githubusercontent.com
151.101.248.133 avatars4.githubusercontent.com
151.101.208.133 avatars5.githubusercontent.com
151.101.208.133 avatars6.githubusercontent.com
151.101.248.133 avatars7.githubusercontent.com
151.101.248.133 avatars8.githubusercontent.com
185.199.110.154 github.githubassets.com
151.101.248.133 user-images.githubusercontent.com
140.82.113.10 codeload.github.com
140.82.121.6 api.github.com
# GitHub End
```

**Comment by allenChn** [comment]
感谢！
